FROM python:2

LABEL maintainer="rizwan@celestialsys.com"

ARG PackageName
ARG PackageVersion
ARG NexusUser
ARG NexusPassword
RUN apt update -y && \
    apt install -y npm nodejs jq unzip curl wget

WORKDIR /usr/src/app
COPY . .

RUN wget --no-check-certificate --user ${NexusUser}  --password ${NexusPassword} https://nexus.tools.froala-infra.com/repository/Froala-npm/${PackageName}/-/${PackageName}-${PackageVersion}.tgz

RUN pip install django
RUN pip install wand
RUN npm install -g bower
RUN bower install

RUN rm -rf bower_components/froala-wysiwyg-editor/


#RUN wget --no-check-certificate --user ${NexusUser}  --password ${NexusPassword} https://nexus.tools.froala-infra.com/repository/Froala-npm/${PackageName}/-/${PackageName}-${PackageVersion}.tgz
RUN tar -xvf ${PackageName}-${PackageVersion}.tgz

RUN mv package/ bower_components/froala-wysiwyg-editor/
RUN rm -rf ${PackageName}-${PackageVersion}.tgz
ENV HOST=0.0.0.0
EXPOSE 8000
WORKDIR django_examples/
ENTRYPOINT python manage.py runserver 0.0.0.0:8000

