FROM python:2

LABEL maintainer="froala_git_travis_bot@idera.com"

ARG PackageName
ARG PackageVersion
ARG NexusUser
ARG NexusPassword

RUN apt update -y && \
    apt install -y npm nodejs jq unzip curl wget

WORKDIR /usr/src/app
COPY . .

RUN wget --no-check-certificate --user ${NexusUser}  --password ${NexusPassword} https://nexus.tools.froala-infra.com/repository/Froala-npm/${PackageName}/-/${PackageName}-${PackageVersion}.tgz

RUN pip install django
RUN pip install wand
RUN npm install -g bower
RUN bower install

EXPOSE 8000
WORKDIR django_examples/
ENTRYPOINT python manage.py runserver 0.0.0.0:8000

